# Generated by Django 2.2.6 on 2021-10-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_auto_20211001_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='strengths',
            field=models.TextField(default='No Strengths? Not much of a Superhero', max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='weakness',
            field=models.TextField(default='no Weaknesses?', max_length=100),
        ),
    ]
