# Generated by Django 2.2.6 on 2021-10-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_auto_20210920_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='strengths',
            field=models.CharField(default='Nothing', max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='description',
            field=models.TextField(default='Nothing'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.CharField(default='/static/unknwn.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(default='No Name', max_length=100),
        ),
    ]
