# Generated by Django 2.2.6 on 2021-10-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_auto_20211001_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.CharField(default='/static/unknown.png', max_length=200),
        ),
    ]
