# Generated by Django 3.2.6 on 2021-10-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0006_auto_20211001_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('markdown', models.TextField()),
                ('html', models.TextField()),
                ('document', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='hero',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
